EcovadisCode/charts

.github/pull_request_template.md, README.md, charts/core/Chart.yaml, charts/core/README.md
Added readme for root directory.
=> Add project readme

README.md
=> Fixed badge

.github/workflows/pr-gate.yaml
=> add tests for dir check

charts/pact-broker/Chart.yaml, charts/pact-broker/templates/deployment.yaml
Checksum annotations added for deployment, so we have pods restarted after deployment if env config related values are changed.
=> Checksum annotations added for deployment

charts/core/Chart.yaml, charts/dotnet-core/Chart.yaml, charts/dotnet-core/templates/deployment.yaml
In order to implement team oriented alerts we need to add "team" label to pods.
https://dev.azure.com/evbts/EcoVadisOps/_workitems/edit/159613 
=> Pod lables

charts/dotnet-core/Readme.md, charts/pact-broker/Chart.yaml, charts/pact-broker/README.md, charts/pact-broker/templates/deployment.yaml, charts/pact-broker/templates/ingress.yaml, charts/pact-broker/templates/service.yaml, charts/pact-broker/values.yaml
Readme file fulfilled.
Values names optimization.
NodePort service type and its values settings are removed.
=> Pact broker chart - Readme/values optimization

charts/core/Chart.yaml, charts/core/README.md, charts/core/templates/CRD/ingressroute.yaml, charts/core/templates/tests/ingressroute_test.py, charts/core/values.yaml
Add retry and circuit breaker middlewares
=> add retry and circuit breaker middlewares

charts/dotnet-core/Chart.yaml
Update dotnet-service chart to include new core chart version
=> upgrade versions

charts/core/Chart.yaml, charts/core/templates/CRD/ingressroute.yaml
=> Attempts type fix

charts/dotnet-core/Chart.yaml
Use fixed charts-core in charts-dotnet
=> use upgraded charts-core

charts/dotnet-core/Chart.yaml
Updated dependencies to use charts-core version 1.2.0
=> updated versions

.gitignore
Corrected entries in gitignore.
=> corrected gitignore for cached charts, ignore temporary rendered files

charts/core/Chart.yaml, charts/core/templates/network-policy.yaml
=> Elastic cloud port

charts/dotnet-core/Chart.yaml
=> core chat version bumped

.github/workflows/pr-gate.yaml, charts/core/Chart.yaml, charts/core/templates/CRD/ingressroute.yaml, charts/core/templates/tests/ingressroute_test.py
=> enable retry middleware by default

charts/dotnet-core/Chart.yaml
=> core chart version bump

charts/core/Chart.yaml, charts/core/templates/CRD/metrictemplate.yaml, charts/core/templates/network-policy.yaml, charts/core/values.yaml
Network policy for mongodb atlas port range, metric template conditions update
=> Core chart: Network policy for mongodb atlas port range

charts/dotnet-core/Chart.yaml, charts/dotnet-core/values.yaml
Version increase for core chart
=> dotnet-core version

charts/core/Chart.yaml
Revert description for core chart
=> Revert description for core chart

.github/pull_request_template.md, charts/cron-job/.gitignore, charts/cron-job/.helmignore, charts/cron-job/Chart.yaml, charts/cron-job/README.md, charts/cron-job/templates/_helpers.tpl, charts/cron-job/templates/appsettings-secret.yaml, charts/cron-job/templates/cronjob.yaml, charts/cron-job/values.yaml
=> Cron job chart migration

charts/dotnet-core/Chart.yaml, charts/dotnet-core/templates/deployment.yaml
POD_NAME env variable added to pod template in order to have an ability for sending it to elastic.
=> Pod name environment variable

charts/dotnet-core/Chart.yaml, charts/dotnet-core/values.yaml
bumped core chart version for dotnet chart
=> bumped core chart version for dotnet chart

charts/dotnet-core/Chart.yaml, charts/dotnet-core/templates/deployment.yaml
Changed topology constrain to ScheduleAnyway
To utilize aks nodes in better way
=> change topology constrains to ScheduleAnyway

charts/dotnet-core/Chart.yaml, charts/dotnet-core/templates/deployment.yaml
increased time for readiness probe
- [x ] dotnet-template
=> Readiness timeout change

.github/pull_request_template.md, charts/app-reverse-proxy/.helmignore, charts/app-reverse-proxy/Chart.yaml, charts/app-reverse-proxy/templates/_helpers.tpl, charts/app-reverse-proxy/templates/appsettings-secret.yaml, charts/app-reverse-proxy/templates/deployment.yaml, charts/app-reverse-proxy/templates/hpa.yaml, charts/app-reverse-proxy/templates/reverse-proxy-configmap.yaml, charts/app-reverse-proxy/templates/service.yaml, charts/app-reverse-proxy/values.yaml
Add app-reverse-proxy Helm chart, update PR template.
=> Rev proxy chart

charts/cron-job/Chart.yaml, charts/cron-job/values.yaml
Fix affinity value 
- [x ] Description provided
=> fix value in affinity

charts/app-reverse-proxy/Chart.yaml, charts/cron-job/Chart.yaml, charts/dotnet-core/Chart.yaml
Update of chart dependency - core chart.
=> Dotnet core core bump

charts/job/.gitignore, charts/job/.helmignore, charts/job/Chart.yaml, charts/job/README.md, charts/job/templates/_helpers.tpl, charts/job/templates/appsettings-secret.yaml, charts/job/templates/job.yaml, charts/job/templates/scaled-object.yaml, charts/job/templates/trigger-authentication.yaml, charts/job/values.yaml
Initial version of a new job helm chart
https://dev.azure.com/evbts/EcoVadisOps/_workitems/edit/202292
=> initial job template

charts/dotnet-core/Chart.yaml
=> version bump

charts/cron-job/Chart.yaml, charts/cron-job/values.yaml
Fix for failing containers startup when there are problems with communication to container registry
=> Cronjobs chart - pull request policy IfNotPresent

charts/core/Chart.yaml, charts/core/templates/CRD/ingressroute.yaml
update traefik crds to use v3 
=> update traefik crds

charts/core/Chart.yaml
Dummy PR to fix release of core chart.
=> Update version of core chart without changes in code

charts/app-reverse-proxy/Chart.yaml, charts/core/Chart.yaml, charts/cron-job/Chart.yaml, charts/dotnet-core/Chart.yaml, charts/job/Chart.yaml
Attempt # 2 to fix broken chart releaser.
=> Dummy update of all charts

charts/app-reverse-proxy/Chart.yaml, charts/app-reverse-proxy/values.yaml, charts/cron-job/Chart.yaml, charts/cron-job/values.yaml, charts/dotnet-core/Chart.yaml, charts/dotnet-core/values.yaml, charts/job/Chart.yaml, charts/job/values.yaml
Update all chart's dependency version - core chart.
Cleanup values.yaml and move network policy values.
=> Bump chart versions and cleanup and move values in values.yaml files

charts/app-reverse-proxy/Chart.yaml, charts/app-reverse-proxy/values.yaml
Updated tag for reverse proxy - alpine3.21-perl
=> new reverse proxy

.github/pull_request_template.md, charts/ado-build-agents/.helmignore, charts/ado-build-agents/Chart.yaml, charts/ado-build-agents/templates/scalejob.yaml, charts/ado-build-agents/templates/secret.yaml, charts/ado-build-agents/templates/service-account.yaml, charts/ado-build-agents/templates/sysbox.yml, charts/ado-build-agents/templates/triggerauth.yaml, charts/ado-build-agents/values.yaml
=> Added chart to deplot azure devops build agents

charts/ado-build-agents/Chart.yaml, charts/ado-build-agents/templates/scalejob-staging.yaml, charts/ado-build-agents/values.yaml
=> Ado build staging

charts/dotnet-core/Chart.yaml, charts/dotnet-core/templates/deployment.yaml, charts/dotnet-core/templates/file-share-secret.yaml, charts/dotnet-core/templates/tests/deployment_test.py, charts/dotnet-core/values.yaml
=> Add file share mount
