- charts/dotnet-core/Chart.yaml
- charts/dotnet-core/templates/hpa.yaml
Recent bump in HPA API caused error in helm chart.
Adjusted HPA to work in v2beta2.
> Fixed hpa in v2beta2

- charts/pact-broker/Chart.yaml
- charts/pact-broker/templates/_helpers.tpl
- charts/pact-broker/templates/deployment.yaml
- charts/pact-broker/templates/env-configmap.yaml
- charts/pact-broker/templates/env-secret.yaml
- charts/pact-broker/templates/ingressroute.yaml
- charts/pact-broker/templates/service.yaml
- charts/pact-broker/templates/serviceaccount.yaml
- charts/pact-broker/values.yaml
Traefik IngressRoute CRD is added, so now there is basic ingress support without TLS configured.
Some cosmetic changes to labels.
> Pact broker chart

- charts/dotnet-core/Chart.yaml
- charts/pact-broker/README.md
> charts-core version bump, Readme change to trigger chart releaser

- charts/core/Chart.yaml
- charts/core/templates/network-policy.yaml
- charts/dotnet-core/Chart.yaml
I want to allow network flow to elastic outside of the cluster, may it be for Cluster A/B or ElasticCloud scenarios.
> Elastic outside cluster

- charts/dotnet-core/Chart.yaml
It seems that core chart needs to be published first before new version may be referenced in dotnet chart
> two step version upgrade

- charts/dotnet-core/Chart.yaml
- charts/dotnet-core/templates/CRD/canary.yaml
- charts/dotnet-core/templates/_helpers.tpl
- charts/dotnet-core/templates/deployment.yaml
- charts/dotnet-core/templates/hpa.yaml
- charts/dotnet-core/templates/service.yaml
- charts/dotnet-core/values.yaml
New major version of dotnet template chart brings canary deployments support
> Canary deployments support - dotnet template chart

- charts/core/Chart.yaml
- charts/core/templates/CRD/metrictemplate.yaml
- charts/core/templates/CRD/servicemonitor.yaml
- charts/core/templates/network-policy.yaml
- charts/core/templates/tests/networkpolicy_test.py
- charts/core/values.yaml
Container metrics for prometheus support added.
Other fixes for canary deployments feature
> Core chart metrics support

- charts/dotnet-core/Chart.yaml
- charts/dotnet-core/templates/CRD/canary.yaml
- charts/dotnet-core/templates/deployment.yaml
- charts/dotnet-core/templates/service.yaml
- charts/dotnet-core/values.yaml
- New option to do a 'force deployment', so error-rate and latency metrics will be bypassed (will be set to 100).
- Load testing webhook enable/disable switch tokenized in values.yaml, thus it is disabled by default.
- Other fixes and improvements.
> Force deploy support, other fixes

- charts/dotnet-core/Chart.yaml
- charts/dotnet-core/templates/CRD/canary.yaml
- charts/dotnet-core/templates/_helpers.tpl
- charts/dotnet-core/values.yaml
Traefik settings moved to helpers out of values.yaml (there is a possibility to override them from values.yaml still)
Some defaults in values.yaml are changed
> traefik settings defaulted in helpers.tpl, some default values changed

- charts/core/Chart.yaml
- charts/core/templates/network-policy.yaml
- charts/core/templates/tests/networkpolicy_test.py
- charts/core/values.yaml
We need a network policy to access the external Zyte proxy service.
> Update chart with new policy, bumped version

- .gitignore
- charts/dotnet-core/Chart.yaml
- charts/dotnet-core/templates/deployment.yaml
- charts/dotnet-core/templates/tests/deployment_test.py
I found an issue where default values are not set correctly because the path to defaults was incorrect. Corrected that path and extended the tests.
> corrected default value path in deployment template, bumped version

- charts/dotnet-core/Chart.yaml
- charts/dotnet-core/templates/deployment.yaml
The way in which pod annotations are templated from values.yaml has changed. It will allow to set pod annotations from --set console command.
> Pod annotations in deployment spec

- charts/core/Chart.yaml
- charts/core/templates/CRD/metrictemplate.yaml
There is an error in metric template - response code 'status' label doesn't exist in metric 'http_requests_received_total'. It changed to proper 'code' label.
> Metric template response code fix

- charts/core/Chart.yaml
- charts/core/templates/network-policy.yaml
Network policy had missing ports when connecting to Atlas Mongo DB - cluster configuration - each shard works on 
port: 1024 ,1025,1026. I was causing issues 
- [x ] core
- [x ] Description provided
- [x ] Chart version bumped
> Mongodb ports - adding ports for shards in cluster configuration

- charts/dotnet-core/Chart.yaml
- charts/dotnet-core/values.yaml
US 181227
default APM configuration to ignore urls for metrics and readyz
> add ignore urls for metrics and readyz

- charts/core/Chart.yaml
- charts/core/templates/pod-disruption-budget.yaml
This version brings support fix for PDB - it will consider -primary pods if canary is enabled
> PDB flagger support

- charts/dotnet-core/Chart.yaml
- charts/dotnet-core/templates/CRD/canary.yaml
- charts/dotnet-core/templates/service.yaml
This version brings support for disabling Canary deployments without downtime.
> Canary revert support

- charts/core/Chart.yaml
- charts/core/templates/CRD/metrictemplate.yaml
Aggregation changed from sum to avg in metric template for canary deployments.
> Canary: Avg aggregation for response time metric in MetricTemplate

- charts/dotnet-core/Chart.yaml
- charts/dotnet-core/values.yaml
> legacy traceparent apm agent header backwards compatibility switched off

- charts/cron-job/Chart.yaml
- charts/cron-job/values.yaml
- charts/dotnet-core/Chart.yaml
- charts/dotnet-core/values.yaml
As we are started to set network policies per-namespace instead of per-app, default value for network policy for charts is set to 'false'
> Disable default Network Policy

- charts/cron-job/Chart.yaml
- charts/cron-job/templates/cronjob.yaml
- charts/cron-job/values.yaml
All aks jobs from now will be assigned to nodepool with tags aksjobs:true
backoffLimit is set to 2
> cron jobs with dedicated nodepool and backofflimit

- charts/app-reverse-proxy/Chart.yaml
- charts/app-reverse-proxy/templates/_helpers.tpl
- charts/app-reverse-proxy/values.yaml
Align reverse proxy chart with all charts - add additional labels support.
> Additional labels support for reverse proxy chart

- charts/core/Chart.yaml
- charts/core/templates/network-policy.yaml
To access elastic cloud via public  url instead of via private link we need to allow public egress connection on this port
> core chart elastic cloud public access enabled via 9243 port

- .github/pull_request_template.md
- charts/app-reverse-proxy/Chart.yaml
- charts/app-reverse-proxy/values.yaml
- charts/cron-job/Chart.yaml
- charts/cron-job/templates/cronjob.yaml
- charts/cron-job/values.yaml
- charts/dotnet-core/Chart.yaml
- charts/dotnet-core/values.yaml
- charts/pact-broker/Chart.yaml
- charts/pact-broker/README.md
- charts/pact-broker/values.yaml
Switching all EV charts to new ACR. All images are already there, Helm deployment is tested with those changes.
Additionally - enabling ACR cache feature for first single rule: dockerhub.
> Switch to new ACR and apply settings for ACR cache rule - dockerhub

- charts/app-reverse-proxy/values.yaml
- charts/core/templates/network-policy.yaml
- charts/core/values.yaml
- charts/cron-job/values.yaml
- charts/dotnet-core/values.yaml
- charts/job/values.yaml
> networkpolicy without vnet

- charts/job/Chart.yaml
- charts/job/templates/job.yaml
- charts/job/templates/trigger-authentication.yaml
- charts/job/values.yaml
Adding support of multiple service bus triggers for single job.
> multiple sb triggers support

- charts/core/Chart.yaml
- charts/core/templates/network-policy.yaml
Hi,
we had connection issues to the Azure SQL with the network policies. Reading about it [here](https://learn.microsoft.com/en-us/azure/azure-sql/database/connectivity-architecture?view=azuresql#connection-policy) the reason was most likely that we only opened port 1433. However, since 
**Redirect** is the default and recommended connection policy all ports in the range 11000-11999 need to be opened, not just 1433.
> opening port 11000 to 11999 for azure sql

- charts/cron-job/Chart.yaml
- charts/cron-job/templates/cronjob.yaml
- charts/cron-job/values.yaml
- charts/job/Chart.yaml
- charts/job/templates/job.yaml
- charts/job/values.yaml
- Adding parallelism value for keda job and CronJob, + completions value for keda job.
- Enhance description of parameters in values.yaml
> Additional parametrization for keda Job and CronJob charts

- charts/dotnet-core/Chart.yaml
- charts/dotnet-core/templates/deployment.yaml
- charts/dotnet-core/values.yaml
Secret provider as variable (do mount different secret during helm chart deployment - its required for using ecovadis.com cert)
> secretProviderClass as variable

- charts/dotnet-core/Chart.yaml
- charts/dotnet-core/templates/deployment.yaml
- charts/dotnet-core/values.yaml
- Fix error of incorrect value of both Flagger's and k8s deployment's progressDeadlineSeconds, since this setting is fixed on Flagger side in latest version.
- Adjust canary rollout analysis timings: set max percentage of traffic 60 -> 70% and weight of step 5 -> 10%.
> Fix progressDeadlineSeconds for k8s deployment and Flagger

- charts/app-reverse-proxy/Chart.yaml
- charts/app-reverse-proxy/templates/appsettings-secret.yaml
- charts/cron-job/Chart.yaml
- charts/cron-job/templates/appsettings-secret.yaml
- charts/dotnet-core/Chart.yaml
- charts/dotnet-core/templates/appsettings-secret.yaml
- charts/job/Chart.yaml
- charts/job/templates/appsettings-secret.yaml
This is a mitigation for these issues with stringData:
https://github.com/kubernetes/kubernetes/issues/89938
https://github.com/helm/helm/issues/10010
https://kubernetes.io/docs/concepts/configuration/secret/#restriction-names-data
Without the fix if secret is created from 2 json files (eg. input1.json and input2.json) removing input2.json file won't remove corresponding key from the secret itself - it will stay there.
> Appsettings secret using data instead of stringData

- charts/cron-job/Chart.yaml
- charts/cron-job/templates/cronjob.yaml
- charts/cron-job/values.yaml
- charts/job/Chart.yaml
- charts/job/values.yaml
Add settings for cron-job history limits, adjust history limits for keda jobs.
There are no settings for cron-job, also adjusting limits for keda scaled jobs.
New default values:
cron-job:
- successful job limit: 1
- failed job limit: 1
keda-job:
- successful job limit: 2
- failed job limit: 1
>  Add settings for cron-job history limits, adjust history limits for keda jobs.

- charts/cron-job/Chart.yaml
- charts/cron-job/values.yaml
- charts/dotnet-core/Chart.yaml
- charts/dotnet-core/templates/service.yaml
- Fix for targetPort in service for workload: port name is now used instead of numeric port number
- Bonus: Removed ports from values of cron-job chart
> dotnet-core chart: Use port name instead of numeric value

- charts/dotnet-core/Chart.yaml
- charts/dotnet-core/templates/deployment.yaml
- charts/dotnet-core/templates/service.yaml
- charts/dotnet-core/templates/tests/secret_appsetting_test.py
- charts/dotnet-core/values.yaml
Following previous PR, doing the same for monitoring port and targeting it in Service by port name instead of port number.
Also updated structure of port values in chart's values.yaml
> Target monitoring port of pod by name instead of port number

- charts/dotnet-core/Chart.yaml
- charts/dotnet-core/templates/deployment.yaml
- charts/dotnet-core/values.yaml
This PR bring support of startup probe for .net container and mock server container.
It is disabled by default and corresponding commented sections are added to chart's values.yaml file.
> Startup probe support

- charts/dotnet-core/Chart.yaml
- charts/dotnet-core/values.yaml
Added /livez to ignored urls in order to reduce apm trace logs
> Added livez endpoint to ignore url for apm

- charts/dotnet-core/Chart.yaml
- charts/dotnet-core/templates/deployment.yaml
- charts/dotnet-core/templates/tests/deployment_test.py
- charts/dotnet-core/values.yaml
Adding second default topology spread constraint as it will help distribute pods across nodes more equally if possible.
In case of unsatisfying any constraint, pod will be scheduled anyway. 
> Add second default topology spread constraint

- charts/dotnet-core/Chart.yaml
- charts/dotnet-core/values.yaml
From now on /readyz and /livez endpoints will be dropped at the ingest pipeline level in Elasticsearch.
> Restored ignored endpoints

- charts/app-reverse-proxy/values.yaml
- charts/core/templates/network-policy.yaml
- charts/core/values.yaml
- charts/cron-job/values.yaml
- charts/dotnet-core/values.yaml
- charts/job/values.yaml
Remove elastic related config which is not anymore used in kubernetes deployment
> chore: remove elastic related config

- charts/ado-build-agents/Chart.yaml
- charts/ado-build-agents/templates/scalejob-staging.yaml
- charts/ado-build-agents/templates/scalejob.yaml
Refactored permissions for rootless buildkit, changed script to look for liveness of build agent container and graceful shutdown
> Refactored buildkit rootless privileges

- charts/cron-job/Chart.yaml
- charts/cron-job/values.yaml
- charts/dotnet-core/Chart.yaml
- charts/dotnet-core/values.yaml
- charts/event-worker/Chart.yaml
- charts/event-worker/values.yaml
- charts/job/Chart.yaml
- charts/job/values.yaml
- charts/pact-broker/Chart.yaml
- charts/pact-broker/values.yaml
We are not using these secrets anymore and they create unnecessary warnings in deployments:
```
FailedToRetrieveImagePullSecret
Unable to retrieve some image pull secrets (acr-pull-secret); attemtping to pull the image may not succeed.
```
- [x ] app-reverse-proxy
> remove acr-pull-secret from values

- charts/ado-build-agents/Chart.yaml
- charts/ado-build-agents/templates/service-account.yaml
- charts/ado-build-agents/templates/triggerauth.yaml
- charts/ado-build-agents/values.yaml
Allows specyfing separate identites used for Keda and build agent
> Separated identity used by Keda ADO autoscaler
